### PR TITLE
update: nordvpn openvpn files

### PR DESCRIPTION
**Pull request by PaulMonnery**
I've been having a problem lately, my container was endlessly rebooting due to a AUTH_FAILING error when openvpn was connecting to nordvpn's servers. The origin of the problem was that the server I was using didn't exist anymore (`fr216.nordvpn.com.udp`)

Currently for France, the only one that hasn't been removed yet is the `fr260`
It seems nordvpn updated their openvpn files, so I downloaded them all from [this page](https://nordvpn.com/ovpn/)

Hope it helps!

### CODE REVIEW

**Comment by Vorsku** [comment]
Thanks!

@sgtsquiggs please could you merge into master and update the docker image? Struggling to find active profiles now for NordVPN

**Comment by sgtsquiggs** [comment]
I do not use NordVPN - if someone would test this and confirm that it works I will merge it.

**Comment by PaulMonnery** [comment]
@Vorsku could you test it ? It works fine for me but I only use french profiles so maybe you'll find errors with other locations

**Comment by Jimbles** [comment]
Further to this, I added some commands to the DockerFile [in my fork](https://github.com/Jimbles/docker-deluge-openvpn) which gets the latest nordvpn profiles and changes the line about `auth-user-pass`. I didnt think a pull request would be appropriate as it adds quite a long build step, which is only necessary for those using nordvpn

**Pull request closed without merging**
